'use client';

import React from 'react';
import { 
  Container, 
    Typography, 
      Button, 
        Grid, 
          Card, 
            CardContent, 
              CardActions,
                Box
                } from '@mui/material';
                import { styled } from '@mui/system';
                import Link from 'next/link';
                import KitchenIcon from '@mui/icons-material/Kitchen';
                import SearchIcon from '@mui/icons-material/Search';
                import CameraAltIcon from '@mui/icons-material/CameraAlt';
                import RestaurantIcon from '@mui/icons-material/Restaurant';

                const StyledCard = styled(Card)(({ theme }) => ({
                  height: '100%',
                    display: 'flex',
                      flexDirection: 'column',
                        transition: 'transform 0.15s ease-in-out',
                          '&:hover': { transform: 'scale3d(1.05, 1.05, 1)' },
                          }));

                          const features = [
                            { 
                                title: 'Manage Your Pantry', 
                                    description: 'Keep track of all your pantry items in one place.',
                                        icon: <KitchenIcon fontSize="large" />,
                                            link: '/dashboard'
                                              },
                                                { 
                                                    title: 'Smart Search', 
                                                        description: 'Quickly find items with our powerful search and filter system.',
                                                            icon: <SearchIcon fontSize="large" />,
                                                                link: '/dashboard'
                                                                  },
                                                                    { 
                                                                        title: 'Image Recognition', 
                                                                            description: 'Add items by simply taking a photo.',
                                                                                icon: <CameraAltIcon fontSize="large" />,
                                                                                    link: '/add-item'
                                                                                      },
                                                                                        { 
                                                                                            title: 'Recipe Suggestions', 
                                                                                                description: 'Get recipe ideas based on your pantry contents.',
                                                                                                    icon: <RestaurantIcon fontSize="large" />,
                                                                                                        link: '/recipes'
                                                                                                          },
                                                                                                          ];

                                                                                                          export default function Home() {
                                                                                                            return (
                                                                                                                <Container maxWidth="lg">
                                                                                                                      <Box sx={{ my: 4 }}>
                                                                                                                              <Typography variant="h2" component="h1" gutterBottom align="center">
                                                                                                                                        Welcome to Pantry Manager
                                                                                                                                                </Typography>
                                                                                                                                                        <Typography variant="h5" component="h2" gutterBottom align="center" color="text.secondary">
                                                                                                                                                                  Organize your kitchen, reduce waste, and cook smarter
                                                                                                                                                                          </Typography>
                                                                                                                                                                                  <Box sx={{ mt: 4, display: 'flex', justifyContent: 'center' }}>
                                                                                                                                                                                            <Button 
                                                                                                                                                                                                        variant="contained" 
                                                                                                                                                                                                                    color="primary" 
                                                                                                                                                                                                                                size="large" 
                                                                                                                                                                                                                                            component={Link} 
                                                                                                                                                                                                                                                        href="/register"
                                                                                                                                                                                                                                                                    sx={{ mr: 2 }}
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                          Get Started
                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                              <Button 
                                                                                                                                                                                                                                                                                                                          variant="outlined" 
                                                                                                                                                                                                                                                                                                                                      color="primary" 
                                                                                                                                                                                                                                                                                                                                                  size="large" 
                                                                                                                                                                                                                                                                                                                                                              component={Link} 
                                                                                                                                                                                                                                                                                                                                                                          href="/login"
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                Log In
                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                  </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                        </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Grid container spacing={4} sx={{ mt: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {features.map((feature, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Grid item key={index} xs={12} sm={6} md={3}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <StyledCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Box sx={{ display: 'flex', justifyContent: 'center', mb: 2 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {feature.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Typography gutterBottom variant="h5" component="div" align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {feature.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Typography variant="body2" color="text.secondary" align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {feature.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardActions sx={{ mt: 'auto', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button size="small" component={Link} href={feature.link}>Learn More</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CardActions>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </StyledCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );}                                                                                                                                                                                                                                                                                                                                                                             