'use client';

import React, { useState } from 'react';
import { Container, Typography, TextField, Button, Box } from '@mui/material';
import { signUp } from '../../lib/auth';
import { useRouter } from 'next/navigation';

export default function Register() {
  const [name, setName] = useState('');
    const [email, setEmail] = useState('');
      const [password, setPassword] = useState('');
        const router = useRouter();

          const handleSubmit = async (e) => {
              e.preventDefault();
                  console.log('Form submitted', { email, password, name }); // Log form submission details
                      try {
                            const user = await signUp(email, password, name);
                                  console.log('User signed up:', user); // Log successful signup
                                        router.push('/login');
                                            } catch (error) {
                                                  console.error('Error signing up:', error);
                                                        alert(`Registration failed: ${error.message}`); // Show detailed error to user
                                                            }
                                                              };

                                                                return (
                                                                    <Container maxWidth="xs">
                                                                          <Box sx={{ mt: 8, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                                                                                  <Typography component="h1" variant="h5">
                                                                                            Register
                                                                                                    </Typography>
                                                                                                    {error && <Alert severity="error" sx={{ mt: 2, width: '100%' }}>{error}</Alert>}
                                                                                                            <Box component="form" onSubmit={handleSubmit} sx={{ mt: 1 }}>
                                                                                                                      <TextField
                                                                                                                                  margin="normal"
                                                                                                                                              required
                                                                                                                                                          fullWidth
                                                                                                                                                                      id="name"
                                                                                                                                                                                  label="Full Name"
                                                                                                                                                                                              name="name"
                                                                                                                                                                                                          autoComplete="name"
                                                                                                                                                                                                                      autoFocus
                                                                                                                                                                                                                                  value={name}
                                                                                                                                                                                                                                              onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                  <TextField
                                                                                                                                                                                                                                                                              margin="normal"
                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                      fullWidth
                                                                                                                                                                                                                                                                                                                  id="email"
                                                                                                                                                                                                                                                                                                                              label="Email Address"
                                                                                                                                                                                                                                                                                                                                          name="email"
                                                                                                                                                                                                                                                                                                                                                      autoComplete="email"
                                                                                                                                                                                                                                                                                                                                                                  value={email}
                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                  <TextField
                                                                                                                                                                                                                                                                                                                                                                                                              margin="normal"
                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                      fullWidth
                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              label="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fullWidth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  variant="contained"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sx={{ mt: 3, mb: 2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
              
                              
                                    
                                    
                                                  
                                    
                                                  

                                                      
                                                    
                                                        
                                                                      
                                                                                
                                                                                      
                                                                                                    
                                                                                                          
                                                                                                                    
                                                                                                                                  
                                                                                                                                      
                                                                                                                                                      
                                                                                                                                                                          
                                                                                                                                                                                      
                                                                                                                                                                                                    
                                                                                                                                                                                                              
                                                                                                                                                                                            
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          
                            
                      
                          
                                        
                                                
                                      

                                                  
                                                
                                                                
  
                                                                  
                                                                              
                                                                                      
                                                                                                    
                                                                                                                      
                                                                                                                    
                                                                                                                          
                                                                                                                                                  
                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                      
                                                                                                                                                                                                  
                                                                                                                                                                                                                    
                                                                                                                                                                                                                      
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                